Allow for NOT NULL constraints
bluemarblepayroll/dbee-active_record pull request #25
Opened 2020-10-09 21:46 UTC by ckattner

- Updates the 'where' predicate builder to allow for IS NOT NULL constraints to be generated.
- Adds test cases to validate generated SQL for several filter scenarios.

2020-10-13 22:02 UTC, gerryster requested changes
Thanks for the fix! The null predicate map seems intuitive. I have a few inline comments for you. The testing approach is commendable in its thoroughness but is a bit heavy handed. Take a look at https://github.com/bluemarblepayroll/dbee-active_record/compare/allow-not-null-constraints...allow-not-null-unit-testing-idea for an idea on how to unit test the where predicates more directly.

Also, don't forget to add yourself as an author in the gemfile!

2020-10-14 21:57 UTC, ckattner commented on lib/dbee/providers/active_record_provider/makers/where.rb
>              predicates.inject(predicates.shift) do |memo, predicate|
`predicates` is used twice, can't remove as a result.

2020-10-14 21:58 UTC, ckattner commented on lib/dbee/providers/active_record_provider/makers/where.rb
> +            predicates
I ended up returning the code to something closer to what it was before, in order to keep rubucop and codeclimate satisfied.  Not convinced it's _better_ necessarily though.

2020-10-14 22:01 UTC, ckattner commented on .rubocop.yml
> +    - spec/dbee/providers/active_record_provider/makers/where_spec.rb
I wouldn't ordinarily do this, but the issue is some expected SQL in the tests that I can't make any shorter and code based alternatives to this are IMO worse than adding this exception.

2020-10-15 20:41 UTC, gerryster requested changes
This is looking good overall. Just one minor suggestion for handling null vs. false.

2020-10-15 20:41 UTC, gerryster commented on lib/dbee/providers/active_record_provider/makers/where.rb
> +            return make_is_null_predicate(arel_column, filter.class) unless filter.value
What about actually doing a `filter.value.nil?` check? It would be strange if this method is invoked for a value of literal `false`.

2020-10-15 21:10 UTC, ckattner commented on lib/dbee/providers/active_record_provider/makers/where.rb
> +            return make_is_null_predicate(arel_column, filter.class) unless filter.value
Good catch.  Updated.

2020-10-15 21:31 UTC, gerryster approved these changes
LGTM. @mattruggio : this one is ready for a final look from you.

2020-10-15 22:01 UTC, mattruggio commented
@ckattner and I had some pretty interesting discussion on the merits of how close this library should be to SQL, versus being an abstraction layer on top of SQL.  The internal issue I have here is the over-abstraction of something and the associated cost to it.  Where this ties back to this specific bug was, how should be handle nulls?  How much should we expose them as a first-class notion more mirroring SQL vs. having our own definition of them.  I think this is a reasonable fix to an obvious bug and it does not really change the definitions or abstractions this library was set out to provide.

2020-10-15 22:02 UTC, mattruggio approved these changes

2020-10-15 22:30 UTC, merged